# Generated by Django 3.1.7 on 2021-04-10 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('currency_a', models.CharField(max_length=5)),
                ('currency_b', models.CharField(max_length=5)),
                ('buy', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buy_status', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('sell', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sell_status', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
